### ISSUE TITLE
Merge to inexor

### ISSUE THREAD

**Issue by Fohlen** [team-cube/open-cube#2]
Hey guys. This is less of an issue and more of a suggestion.
We've been working on @inexorgame for a couple of years (3 years) now and I think it'd be very valuable if you would also push your changes upstream to Inexor!
What you think about this?

**Comment by hhirsch** [comment]
@Fohlen The main thing I fixed in open cube is to have game data as a submodule. It speeds up the cloning process. I've just looked over your repositories and could not see how you solved this problem. 
To me this looks like it can't be done easily in a PR as it deletes files from the repository history.

Open Cube is based on tesseract not on vanilla Cube2 so that might present more problems when trying to merge our work (when there is not a lot of interesting stuff in open cube to merge to begin with).

**Comment by Fohlen** [comment]
Hey @hhirsch we do use submodules. However we will move away from the `cube2` engine. Closing this.
